export const dummyTransactionsData = [
  {
    transactionNumber: 1,
    date: "July-25-23",
    time: "10:00 am",
    amount: "2,515.2",
    paymentType: "Cash",
    businessName: "JK's Papaitan",
    chargeInvoiceNo: "20012",
  },
  {
    transactionNumber: 2,
    date: "August-12-23",
    time: "02:30 pm",
    amount: "1,200.75",
    paymentType: "Credit Card",
    businessName: "Sunny's Grill",
    chargeInvoiceNo: "20013",
  },
  {
    transactionNumber: 3,
    date: "September-05-23",
    time: "08:45 am",
    amount: "850.00",
    paymentType: "Debit Card",
    businessName: "Green Garden Cafe",
    chargeInvoiceNo: "20014",
  },
  {
    transactionNumber: 4,
    date: "October-18-23",
    time: "05:15 pm",
    amount: "3,700.50",
    paymentType: "Mobile Payment",
    businessName: "Spice Kingdom",
    chargeInvoiceNo: "20015",
  },
  {
    transactionNumber: 5,
    date: "November-07-23",
    time: "12:20 pm",
    amount: "500.00",
    paymentType: "Cash",
    businessName: "Mia's Bakery",
    chargeInvoiceNo: "20016",
  },
  {
    transactionNumber: 6,
    date: "December-15-23",
    time: "03:45 pm",
    amount: "1,800.25",
    paymentType: "Credit Card",
    businessName: "Ocean Breeze Restaurant",
    chargeInvoiceNo: "20017",
  },
  {
    transactionNumber: 7,
    date: "January-10-24",
    time: "09:30 am",
    amount: "950.75",
    paymentType: "Debit Card",
    businessName: "Golden Wok",
    chargeInvoiceNo: "20018",
  },
]

export const dummyTableData = [
  {
    fullName: "Mario Bradley",
    userName: "Ethan",
    role: "these",
    company: "once",
    department: "stage",
    location: "spoken",
    // actions: "class",
  },
  {
    fullName: "Lewis Adams",
    userName: "Daniel",
    role: "government",
    company: "meat",
    department: "choose",
    location: "red",
    // actions: "eye",
  },
  // {
  //   fullName: "Milton Wheeler",
  //   userName: "Cameron",
  //   role: "eaten",
  //   company: "stream",
  //   department: "shaking",
  //   location: "weak",
  //   actions: "suppose",
  // },
  // {
  //   fullName: "Mittie Joseph",
  //   userName: "Allie",
  //   role: "flies",
  //   company: "swing",
  //   department: "graph",
  //   location: "pine",
  //   actions: "planet",
  // },
  // {
  //   fullName: "Mae Garcia",
  //   userName: "Jackson",
  //   role: "spread",
  //   company: "angle",
  //   department: "anywhere",
  //   location: "land",
  //   actions: "library",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
];
