export const dummyTransactionsData = [
  {
    id: 1,
    time: "10:00 am",
    amount: "2,515.2",
    paymentType: "Cash",
    businessName: "JK's Papaitan",
    "CINo.": "20012",
    attachmentStatus: true,
  },
  {
    id: 2,
    time: "02:30 pm",
    amount: "1,200.75",
    paymentType: "Credit Card",
    businessName: "Sunny's Grill",
    "CINo.": "20013",
    attachmentStatus: true,
  },
  {
    id: 3,
    time: "08:45 am",
    amount: "850.00",
    paymentType: "Debit Card",
    businessName: "Green Garden Cafe",
    "CINo.": "20014",
    attachmentStatus: false,
  },
  {
    id: 10,
    time: "05:15 pm",
    amount: "3,700.50",
    paymentType: "Mobile Payment",
    businessName: "Spice Kingdom",
    "CINo.": "20015",
    attachmentStatus: true,
  },
  {
    id: 5,
    time: "12:20 pm",
    amount: "500.00",
    paymentType: "Cash",
    businessName: "Mia's Bakery",
    "CINo.": "20016",
    attachmentStatus: true,
  },
  {
    id: 30,
    time: "03:45 pm",
    amount: "1,800.25",
    paymentType: "Credit Card",
    businessName: "Ocean Breeze Restaurant",
    "CINo.": "20017",
    attachmentStatus: false,
  },
  {
    id: 7,
    time: "09:30 am",
    amount: "950.75",
    paymentType: "Debit Card",
    businessName: "Golden Wok",
    "CINo.": "20018",
    attachmentStatus: false,
  },
];

export const dummyAdvancePaymentData = [
  {
    businessName: "Kiana's BBQ and Wings",
    ownersName: "Kiana Kaslana",
    amount: 1000.23,
    paymentType: "Cheque",
    date: "January 10, 2024",
  },
  {
    businessName: "Sunny Delights Bakery",
    ownersName: "Samantha Sunshine",
    amount: 750.5,
    paymentType: "Credit Card",
    date: "February 5, 2024",
  },
  {
    businessName: "Taste of Italy Pizzeria",
    ownersName: "Luigi Rossi",
    amount: 1200.75,
    paymentType: "Cash",
    date: "March 20, 2024",
  },
  {
    businessName: "Spice Paradise Indian Cuisine",
    ownersName: "Raj Patel",
    amount: 900.8,
    paymentType: "Bank Transfer",
    date: "April 15, 2024",
  },
  {
    businessName: "Seafood Haven",
    ownersName: "Marina Fisher",
    amount: 850.25,
    paymentType: "Online Payment",
    date: "May 1, 2024",
  },
  {
    businessName: "Green Harvest Organic Market",
    ownersName: "Emma Greene",
    amount: 600.4,
    paymentType: "Cash",
    date: "June 8, 2024",
  },
];

export const dummyPaymentData = [
  {
    date: "JAN-20-24",
    transactionNo: 1,
    businessName: "Kiana's BBQ and Wings",
    ownersName: "Kiana Kaslana",
    chargeInvoiceNo: 20012,
    amount: 1000.23,
    amountBalance: 500.23,
  },
  {
    date: "FEB-15-24",
    transactionNo: 2,
    businessName: "Sunny Delights Bakery",
    ownersName: "Samantha Sunshine",
    chargeInvoiceNo: 20013,
    amount: 750.5,
    amountBalance: 250.5,
  },
  {
    date: "MAR-10-24",
    transactionNo: 3,
    businessName: "Taste of Italy Pizzeria",
    ownersName: "Luigi Rossi",
    chargeInvoiceNo: 20014,
    amount: 1200.75,
    amountBalance: 600.75,
  },
  {
    date: "APR-05-24",
    transactionNo: 4,
    businessName: "Spice Paradise Indian Cuisine",
    ownersName: "Raj Patel",
    chargeInvoiceNo: 20015,
    amount: 900.8,
    amountBalance: 300.8,
  },
  {
    date: "MAY-01-24",
    transactionNo: 5,
    businessName: "Seafood Haven",
    ownersName: "Marina Fisher",
    chargeInvoiceNo: 20016,
    amount: 850.25,
    amountBalance: 150.25,
  },
  {
    date: "JUN-08-24",
    transactionNo: 6,
    businessName: "Green Harvest Organic Market",
    ownersName: "Emma Greene",
    chargeInvoiceNo: 20017,
    amount: 600.4,
    amountBalance: 200.4,
  },
];

export const dummyTableData = [
  {
    fullName: "Mario Bradley",
    userName: "Ethan",
    role: "these",
    company: "once",
    department: "stage",
    location: "spoken",
    // actions: "class",
  },
  {
    fullName: "Lewis Adams",
    userName: "Daniel",
    role: "government",
    company: "meat",
    department: "choose",
    location: "red",
    // actions: "eye",
  },
  // {
  //   fullName: "Milton Wheeler",
  //   userName: "Cameron",
  //   role: "eaten",
  //   company: "stream",
  //   department: "shaking",
  //   location: "weak",
  //   actions: "suppose",
  // },
  // {
  //   fullName: "Mittie Joseph",
  //   userName: "Allie",
  //   role: "flies",
  //   company: "swing",
  //   department: "graph",
  //   location: "pine",
  //   actions: "planet",
  // },
  // {
  //   fullName: "Mae Garcia",
  //   userName: "Jackson",
  //   role: "spread",
  //   company: "angle",
  //   department: "anywhere",
  //   location: "land",
  //   actions: "library",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
];

export const dummyDataset = [
  {
    amount: 65000.75,
    month: "Jan",
  },
  {
    amount: 70000.5,
    month: "Feb",
  },
  {
    amount: 80000.25,
    month: "Mar",
  },
  {
    amount: 65000.8,
    month: "Apr",
  },
  {
    amount: 90000.4,
    month: "May",
  },
  {
    amount: 60000.6,
    month: "June",
  },
  {
    amount: 95000.3,
    month: "July",
  },
  {
    amount: 80000.9,
    month: "Aug",
  },
  {
    amount: 70000.2,
    month: "Sept",
  },
  {
    amount: 75000.45,
    month: "Oct",
  },
  {
    amount: 85000.7,
    month: "Nov",
  },
  {
    amount: 100000.0,
    month: "Dec",
  },
];

export const dummyInventoryData = [
  {
    id: 1,
    itemCode: "52319",
    itemDescription: "Rapsarap Chicken Nuggets 200g",
    totalStock: 100,
    nearExpiry: 20,
  },
  {
    id: 2,
    itemCode: "74562",
    itemDescription: "Rapsarap Potato Chips 150g",
    totalStock: 80,
    nearExpiry: 15,
  },
  {
    id: 3,
    itemCode: "89234",
    itemDescription: "Rapsarap Chocolate Bars 100g",
    totalStock: 120,
    nearExpiry: 25,
  },
  {
    id: 4,
    itemCode: "31678",
    itemDescription: "Rapsarap Granola 300g",
    totalStock: 150,
    nearExpiry: 30,
  },
  {
    id: 5,
    itemCode: "45791",
    itemDescription: "Rapsarap Popcorn 250g",
    totalStock: 90,
    nearExpiry: 10,
  },
  {
    id: 6,
    itemCode: "62453",
    itemDescription: "Rapsarap Mixed Fruit Jam 400g",
    totalStock: 110,
    nearExpiry: 18,
  },
  {
    id: 7,
    itemCode: "10987",
    itemDescription: "Rapsarap Mixed Nuts 180g",
    totalStock: 70,
    nearExpiry: 12,
  },
  {
    id: 8,
    itemCode: "23564",
    itemDescription: "Rapsarap Cheese Crackers 120g",
    totalStock: 95,
    nearExpiry: 22,
  },
  {
    id: 9,
    itemCode: "78901",
    itemDescription: "Rapsarap Caramel Popcorn 200g",
    totalStock: 120,
    nearExpiry: 15,
  },
  {
    id: 10,
    itemCode: "45623",
    itemDescription: "Rapsarap Almond Chocolate Bars 150g",
    totalStock: 80,
    nearExpiry: 10,
  },
  // {
  //   id: 11,
  //   itemCode: "98765",
  //   itemDescription: "Rapsarap Honey Roasted Peanuts 250g",
  //   totalStock: 110,
  //   nearExpiry: 18,
  // },
  // {
  //   id: 12,
  //   itemCode: "34567",
  //   itemDescription: "Rapsarap Blueberry Jam 300g",
  //   totalStock: 130,
  //   nearExpiry: 25,
  // },
  // {
  //   id: 13,
  //   itemCode: "87654",
  //   itemDescription: "Rapsarap Trail Mix 200g",
  //   totalStock: 75,
  //   nearExpiry: 12,
  // },
  // {
  //   id: 14,
  //   itemCode: "23456",
  //   itemDescription: "Rapsarap Onion Rings 180g",
  //   totalStock: 85,
  //   nearExpiry: 15,
  // },
];

export const dummyPaymentHistoriesData = [
  {
    id: 5,
    date: "2024-04-29T16:55:30",
    total: 150000,
    paymentTypes: [
      {
        paymentType: "Cash",
        amount: 120000,
      },
      {
        paymentType: "Online",
        amount: 30000,
        accountName: "Michael Johnson",
        accountNumber: "1357924680",
        referenceNumber: "987654",
      },
    ],
  },
  {
    id: 4,
    date: "2024-03-25T09:45:12",
    total: 90000,
    paymentTypes: [
      {
        paymentType: "Advance Payment",
        amount: 90000,
      },
    ],
  },
  {
    id: 3,
    date: "2024-03-20T14:30:22",
    total: 120000,
    paymentTypes: [
      {
        paymentType: "Online",
        amount: 120000,
        accountName: "Jane Smith",
        accountNumber: "0987654321",
        referenceNumber: "654321",
      },
    ],
  },
  {
    id: 2,
    date: "2024-03-15T11:20:45",
    total: 180000,
    paymentTypes: [
      {
        paymentType: "Cash",
        amount: 180000,
      },
    ],
  },
  {
    id: 1,
    date: "2024-03-10T10:00:33",
    total: 240000,
    paymentTypes: [
      {
        paymentType: "Cash",
        amount: 100000,
      },
      {
        paymentType: "Cheque",
        amount: 50000,
        payee: "John Doe",
        chequeDate: "2024-03-10",
        bank: "BDO",
        chequeNo: "123456",
        dateReceived: "2024-03-10",
      },
      {
        paymentType: "Online",
        amount: 50000,
        accountName: "John Doe",
        accountNumber: "1234567890",
        referenceNumber: "123456",
      },
      {
        paymentType: "Listing Fee",
        amount: 20000,
      },
      {
        paymentType: "Offset",
        amount: 10000,
        remarks: "Deduct from CDO",
      },
      {
        paymentType: "Advance Payment",
        amount: 10000,
      },
    ],
  },
];

export const dummyOnlinePaymentPlatformsData = [
  {
    id: 1,
    name: "GCash",
  },
  {
    id: 2,
    name: "PayMaya",
  },
  {
    id: 3,
    name: "Coins.PH",
  },
  {
    id: 4,
    name: "BPI",
  },
  {
    id: 5,
    name: "BDO",
  },
  {
    id: 6,
    name: "Metrobank",
  },
  {
    id: 7,
    name: "UnionBank",
  },
  {
    id: 8,
    name: "Security Bank",
  },
  {
    id: 9,
    name: "Landbank",
  },
  {
    id: 10,
    name: "PNB",
  },
  {
    id: 11,
    name: "Metrobank",
  },
  {
    id: 12,
    name: "ChinaBank",
  },
  {
    id: 13,
    name: "PSBank",
  },
  {
    id: 14,
    name: "Maybank",
  },
  {
    id: 15,
    name: "EastWest Bank",
  },
  {
    id: 16,
    name: "UCPB",
  },
  {
    id: 17,
    name: "DBP",
  },
  {
    id: 18,
    name: "HSBC",
  },
  {
    id: 19,
    name: "CIMB",
  },
  {
    id: 20,
    name: "ING",
  },
];

export const dummyListingFeeBalancesData = [
  {
    id: 1,
    businessName: "Kiana's Sushi",
    ownersName: "Kiana Kaslana",
    listingFeeBalance: 70000,
  },
  {
    id: 2,
    businessName: "Bronya's Dumplings",
    ownersName: "Bronya Zaychik",
    listingFeeBalance: 50000,
  },
  {
    id: 3,
    businessName: "Himeko's Ramen",
    ownersName: "Himeko Murata",
    listingFeeBalance: 60000,
  },
  {
    id: 4,
    businessName: "Theresa's Pastries",
    ownersName: "Theresa Apocalypse",
    listingFeeBalance: 80000,
  },
  {
    id: 5,
    businessName: "Fu Hua's Tea House",
    ownersName: "Fu Hua",
    listingFeeBalance: 75000,
  },
];
