export const dummyTransactionsData = [
  {
    id: 1,
    time: "10:00 am",
    amount: "2,515.2",
    paymentType: "Cash",
    businessName: "JK's Papaitan",
    "CINo.": "20012",
    attachmentStatus: true,
  },
  {
    id: 2,
    time: "02:30 pm",
    amount: "1,200.75",
    paymentType: "Credit Card",
    businessName: "Sunny's Grill",
    "CINo.": "20013",
    attachmentStatus: true,
  },
  {
    id: 3,
    time: "08:45 am",
    amount: "850.00",
    paymentType: "Debit Card",
    businessName: "Green Garden Cafe",
    "CINo.": "20014",
    attachmentStatus: false,
  },
  {
    id: 10,
    time: "05:15 pm",
    amount: "3,700.50",
    paymentType: "Mobile Payment",
    businessName: "Spice Kingdom",
    "CINo.": "20015",
    attachmentStatus: true,
  },
  {
    id: 5,
    time: "12:20 pm",
    amount: "500.00",
    paymentType: "Cash",
    businessName: "Mia's Bakery",
    "CINo.": "20016",
    attachmentStatus: true,
  },
  {
    id: 30,
    time: "03:45 pm",
    amount: "1,800.25",
    paymentType: "Credit Card",
    businessName: "Ocean Breeze Restaurant",
    "CINo.": "20017",
    attachmentStatus: false,
  },
  {
    id: 7,
    time: "09:30 am",
    amount: "950.75",
    paymentType: "Debit Card",
    businessName: "Golden Wok",
    "CINo.": "20018",
    attachmentStatus: false,
  },
];

export const dummyAdvancePaymentData = [
  {
    businessName: "Kiana's BBQ and Wings",
    ownersName: "Kiana Kaslana",
    amount: 1000.23,
    paymentType: "Cheque",
    date: "January 10, 2024",
  },
  {
    businessName: "Sunny Delights Bakery",
    ownersName: "Samantha Sunshine",
    amount: 750.5,
    paymentType: "Credit Card",
    date: "February 5, 2024",
  },
  {
    businessName: "Taste of Italy Pizzeria",
    ownersName: "Luigi Rossi",
    amount: 1200.75,
    paymentType: "Cash",
    date: "March 20, 2024",
  },
  {
    businessName: "Spice Paradise Indian Cuisine",
    ownersName: "Raj Patel",
    amount: 900.8,
    paymentType: "Bank Transfer",
    date: "April 15, 2024",
  },
  {
    businessName: "Seafood Haven",
    ownersName: "Marina Fisher",
    amount: 850.25,
    paymentType: "Online Payment",
    date: "May 1, 2024",
  },
  {
    businessName: "Green Harvest Organic Market",
    ownersName: "Emma Greene",
    amount: 600.4,
    paymentType: "Cash",
    date: "June 8, 2024",
  },
];

export const dummyPaymentData = [
  {
    date: "JAN-20-24",
    transactionNo: 1,
    businessName: "Kiana's BBQ and Wings",
    ownersName: "Kiana Kaslana",
    chargeInvoiceNo: 20012,
    amount: 1000.23,
    amountBalance: 500.23,
  },
  {
    date: "FEB-15-24",
    transactionNo: 2,
    businessName: "Sunny Delights Bakery",
    ownersName: "Samantha Sunshine",
    chargeInvoiceNo: 20013,
    amount: 750.5,
    amountBalance: 250.5,
  },
  {
    date: "MAR-10-24",
    transactionNo: 3,
    businessName: "Taste of Italy Pizzeria",
    ownersName: "Luigi Rossi",
    chargeInvoiceNo: 20014,
    amount: 1200.75,
    amountBalance: 600.75,
  },
  {
    date: "APR-05-24",
    transactionNo: 4,
    businessName: "Spice Paradise Indian Cuisine",
    ownersName: "Raj Patel",
    chargeInvoiceNo: 20015,
    amount: 900.8,
    amountBalance: 300.8,
  },
  {
    date: "MAY-01-24",
    transactionNo: 5,
    businessName: "Seafood Haven",
    ownersName: "Marina Fisher",
    chargeInvoiceNo: 20016,
    amount: 850.25,
    amountBalance: 150.25,
  },
  {
    date: "JUN-08-24",
    transactionNo: 6,
    businessName: "Green Harvest Organic Market",
    ownersName: "Emma Greene",
    chargeInvoiceNo: 20017,
    amount: 600.4,
    amountBalance: 200.4,
  },
];

export const dummyTableData = [
  {
    fullName: "Mario Bradley",
    userName: "Ethan",
    role: "these",
    company: "once",
    department: "stage",
    location: "spoken",
    // actions: "class",
  },
  {
    fullName: "Lewis Adams",
    userName: "Daniel",
    role: "government",
    company: "meat",
    department: "choose",
    location: "red",
    // actions: "eye",
  },
  // {
  //   fullName: "Milton Wheeler",
  //   userName: "Cameron",
  //   role: "eaten",
  //   company: "stream",
  //   department: "shaking",
  //   location: "weak",
  //   actions: "suppose",
  // },
  // {
  //   fullName: "Mittie Joseph",
  //   userName: "Allie",
  //   role: "flies",
  //   company: "swing",
  //   department: "graph",
  //   location: "pine",
  //   actions: "planet",
  // },
  // {
  //   fullName: "Mae Garcia",
  //   userName: "Jackson",
  //   role: "spread",
  //   company: "angle",
  //   department: "anywhere",
  //   location: "land",
  //   actions: "library",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
  // {
  //   fullName: "Edwin Adams",
  //   userName: "Barbara",
  //   role: "command",
  //   company: "got",
  //   department: "traffic",
  //   location: "weight",
  //   actions: "father",
  // },
  // {
  //   fullName: "Rena Garza",
  //   userName: "Rhoda",
  //   role: "music",
  //   company: "silent",
  //   department: "someone",
  //   location: "area",
  //   actions: "own",
  // },
];
