export const navigationData = [
  {
    id: 1,
    path: "/",
    name: "Dashboard",
    icon: "Dashboard",
  },
  // {
  //   id: 2,
  //   path: "/",
  //   name: "Dashboard",
  //   icon: "Dashboard",
  // },
  {
    id: 3,
    path: "/user-management",
    name: "User Management",
    icon: "AccountCircle",
    sub: [
      {
        id: 1,
        name: "User Account",
        path: "/user-management/user-account",
        icon: "Person",
        description: "Manage and create user accounts based on SEDAR",
      },
      {
        id: 2,
        name: "User Role",
        path: "/user-management/user-role",
        icon: "SupervisorAccount",
        description: "Manage and tag user roles",
      },
      {
        id: 3,
        name: "Approver",
        path: "/user-management/approver",
        icon: "HowToVote",
        description: "Manage list and ordering of approvers",
      },
      {
        id: 4,
        name: "Cluster",
        path: "/user-management/cluster",
        icon: "PinDrop",
        description: "Manage clusters with tagged CDOs",
      },
      // {
      //   id: 5,
      //   name: "Company",
      //   path: "/user-management/company",
      //   icon: "Business",
      //   description: "Manage and sync company to FISTO"
      // },
      // {
      //   id: 6,
      //   name: "Department",
      //   path: "/user-management/department",
      //   icon: "BusinessCenter",
      //   description: "Manage and sync department to FISTO"
      // },
      // {
      //   id: 7,
      //   name: "Location",
      //   path: "/user-management/location",
      //   icon: "LocationOn",
      //   description: "Manage and sync location to FISTO"
      // },
    ],
  },
  {
    id: 4,
    path: "/product-setup",
    name: "Product Setup",
    icon: "Dataset",
    sub: [
      {
        id: 1,
        name: "Products",
        path: "/product-setup/products",
        icon: "LocalMall",
        description: "Manage and create product items",
      },
      {
        id: 2,
        name: "Product Category",
        path: "/product-setup/product-category",
        icon: "Category",
        description: "Manage and create product category",
      },
      {
        id: 3,
        name: "Product Sub Category",
        path: "/product-setup/product-sub-category",
        icon: "SubdirectoryArrowRight",
        description: "Manage and create product sub category",
      },
      {
        id: 4,
        name: "Meat Type",
        path: "/product-setup/meat-type",
        icon: "RestaurantMenu",
        description: "Manage and create meat types",
      },
      {
        id: 5,
        name: "Unit of Measurements",
        path: "/product-setup/uom",
        icon: "SquareFoot",
        description: "Manage and create unit of measurements",
      },
      {
        id: 6,
        name: "Price Mode Setup",
        path: "/product-setup/price-mode-setup",
        icon: "Settings",
        description: "Manage and create price modes",
      },
      {
        id: 7,
        name: "Price Mode Management",
        path: "/product-setup/price-mode-management",
        icon: "Link",
        description: "Tagging of items and price change for each price mode",
      },
    ],
  },

  {
    id: 5,
    path: "/customer-management",
    name: "Customer Management",
    icon: "SupervisedUserCircle",
    sub: [
      {
        id: 1,
        name: "Business Type",
        path: "/customer-management/business-type",
        icon: "StoreMallDirectory",
        description: "Manage and create business type",
      },
      {
        id: 2,
        name: "Variable Discount",
        path: "/customer-management/variable-discount",
        icon: "Label",
        description: "Manage variable discount amount and percentage ranges",
      },
      {
        id: 3,
        name: "Term Days",
        path: "/customer-management/term-days",
        icon: "CalendarToday",
        description: "Manage and create term days",
      },
      {
        id: 4,
        name: "Expenses Setup",
        path: "/customer-management/expenses-setup",
        icon: "AttachMoney",
        description: "Manage and create other expenses",
      },
    ],
  },

  {
    id: 7,
    path: "/customer-registration",
    name: "Customer Registration",
    icon: "AddBusiness",
    notifications: ["rejectedClient", "rejectedListingFee", "rejectedExpenses"],
    sub: [
      {
        id: 1,
        path: "/customer-registration/prospect",
        name: "Prospect",
        icon: "AccountBox",
        description: "Prospecting of potential clients through freebies",
        notifications: ["prospect"],
      },
      {
        id: 2,
        path: "/customer-registration/registration",
        name: "Registration",
        icon: "PersonAdd",
        description: "Directly register clients and track their approval",
        notifications: ["rejectedClient"],
      },
      {
        id: 3,
        path: "/customer-registration/listing-fee",
        name: "Listing Fee",
        icon: "Payment",
        description:
          "Requesting and tracking of listing fees for desired items",
        notifications: ["rejectedListingFee"],
      },
      {
        id: 4,
        path: "/customer-registration/other-expenses",
        name: "Other Expenses",
        icon: "AttachMoney",
        description: "Requesting and tracking of other expenses",
        notifications: ["rejectedExpenses"],
      },
      // {
      //   id: 4,
      //   path: "/customer-registration/freebies",
      //   name: "Freebies",
      //   icon: "CardGiftCard",
      // },
    ],
  },

  {
    id: 8,
    path: "/sales-management",
    name: "Sales Management",
    icon: "TrendingUp",
    sub: [
      {
        id: 1,
        path: "/sales-management/sales-transaction",
        name: "Sales Transaction",
        icon: "MonetizationOn",
        description: "POS and transactions list with attaching of CI photo",
      },
      {
        id: 2,
        path: "/sales-management/payment-transaction",
        name: "Payment Transaction",
        icon: "Payment",
        description: "Manage and create payments",
      },
      {
        id: 3,
        path: "/sales-management/special-discount",
        name: "Special Discount",
        icon: "Discount",
        description: "Manage and create special discounts",
      },
      {
        id: 4,
        path: "/sales-management/advance-payment",
        name: "Advance Payment",
        icon: "FastForward",
        description: "Manage and create advance payments",
      },
    ],
  },

  // {
  //   id: 8,
  //   path: "/freebies",
  //   name: "Freebies",
  //   icon: "PostAdd",
  // },
  {
    id: 9,
    path: "/approval",
    name: "Approval",
    icon: "Approval",
    notifications: ["pendingClient", "pendingListingFee", "pendingExpenses"],
    sub: [
      {
        id: 1,
        name: "Registration Approval",
        path: "/approval/registration-approval",
        icon: "HowToReg",
        description: "Approval and rejection of client registration requests",
        notifications: ["pendingClient"],
      },
      {
        id: 2,
        name: "Sp. Discount Approval",
        path: "/approval/sp-discount-approval",
        icon: "LocalOffer",
        description: "Approval and rejection of sp. discount requests",
        // notifications: "pendingSpDiscount",
      },
      {
        id: 3,
        name: "Listing Fee Approval",
        path: "/approval/listing-fee-approval",
        icon: "Payment",
        description: "Approval and rejection of listing fee requests",
        notifications: ["pendingListingFee"],
      },
      // {
      //   id: 4,
      //   name: "Freebie Approval",
      //   path: "/approval/freebie-approval",
      //   icon: "Redeem",
      // },
      {
        id: 4,
        name: "Other Expenses Approval",
        path: "/approval/other-expenses-approval",
        icon: "AttachMoney",
        description: "Approval and rejection of other expenses requests",
        notifications: ["pendingExpenses"],
      },
    ],
  },
  // {
  //   id: 10,
  //   path: "/inventory",
  //   name: "Inventory",
  //   icon: "Inventory",
  //   sub: [
  //     {
  //       id: 1,
  //       name: "MRP",
  //       path: "/inventory/mrp",
  //     },
  //     {
  //       id: 2,
  //       name: "Other",
  //       path: "/inventory/other",
  //     },
  //   ],
  // },
];
